### ISSUE TITLE
tikz figures missing

### ISSUE THREAD

**Issue by msbauer** [eklenske/thesis#1]
When compiling the document, pdflatex complains that a lot of tikz figures are missing, e.g.:
```
! LaTeX Error: File ` fig/toy_example.tikz' not found.
```
Am I doing something stupid or did you forget to commit these files?

**Comment by eklenske** [comment]
I used a quite general `.gitignore` which included `*.tikz`. Sorry about that. I added all `tikz`-pictures and now it should work.
